import AuthProvider from '@/components/AuthProvider'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth/next'
import { Inter } from 'next/font/google'
import { authOptions } from './api/auth/[...nextauth]/route'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <AuthProvider session={session}>
        <body className={inter.className}>{children}</body>
      </AuthProvider>
    </html>
  )
}
